<?php

namespace BpopWebsiteBundle\Repository;

/**
 * GaleryFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GaleryFileRepository extends \Doctrine\ORM\EntityRepository
{
}
