<?php

namespace BpopWebsiteBundle\Repository;

/**
 * MusicShowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MusicShowRepository extends \Doctrine\ORM\EntityRepository
{
}
