<?php

namespace BpopWebsiteBundle\Repository;

/**
 * RecordingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecordingRepository extends \Doctrine\ORM\EntityRepository
{
}
