bpop_website_news:
    path:     /news/{page}
    defaults: 
        _controller: BpopWebsiteBundle:News:index
        page:        1
    requirements:
        page: \d*
        
bpop_website_music:
    path:     /music
    defaults:
        _controller: BpopWebsiteBundle:Music:index
        
bpop_website_gallery:
    path:     /gallery/{page}
    defaults:
        _controller: BpopWebsiteBundle:Gallery:index
        page:        1
    requirements:
        page: \d*
